# Generated by Django 5.2.17 on 2026-09-25 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_widget_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('agent_type', models.CharField(choices=[('sales', 'Sales'), ('support', 'Support'), ('combined', 'Combined')], default='combined', max_length=16)),
                ('primary_goal', models.CharField(choices=[('sales', 'Sales'), ('customer_support', 'Customer Support'), ('sales_and_support', 'Sales & Support'), ('lead_generation', 'Lead Generation'), ('information', 'Information')], default='sales_and_support', max_length=32)),
                ('secondary_goals', models.JSONField(blank=True, default=list)),
                ('system_prompt', models.TextField(blank=True, help_text='Business-authored instructions. Rendered as AGENT CONFIGURATION in the prompt hierarchy — cannot override SYSTEM instructions.')),
                ('greeting', models.TextField(blank=True)),
                ('language', models.CharField(default='en', max_length=16)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('casual', 'Casual'), ('formal', 'Formal')], default='professional', max_length=16)),
                ('must_always_mention', models.JSONField(blank=True, default=list)),
                ('must_never_say', models.JSONField(blank=True, default=list)),
                ('escalation_rules', models.JSONField(blank=True, default=list, help_text='List of trigger phrases/conditions that force human handoff.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disabled', 'Disabled')], default='draft', max_length=16)),
                ('model', models.CharField(default='gpt-4o-mini', max_length=128)),
                ('temperature', models.FloatField(default=0.4)),
                ('max_tokens', models.PositiveIntegerField(default=800)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.business')),
            ],
            options={
                'db_table': 'agents_agent',
            },
        ),
        migrations.CreateModel(
            name='AgentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128)),
                ('value', models.JSONField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='agents.agent')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.business')),
            ],
            options={
                'db_table': 'agents_agent_setting',
            },
        ),
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_name', models.CharField(choices=[('create_lead', 'Create Lead'), ('update_lead', 'Update Lead'), ('request_demo', 'Request Demo'), ('request_callback', 'Request Callback'), ('create_ticket', 'Create Support Ticket'), ('create_payment_link', 'Create Payment Link'), ('create_quote', 'Create Quote'), ('book_appointment', 'Book Appointment'), ('human_handoff', 'Human Handoff')], max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('permission_level', models.CharField(choices=[('auto', 'Execute automatically'), ('requires_approval', 'Requires human approval')], default='auto', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='agents.agent')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.business')),
            ],
            options={
                'db_table': 'agents_agent_tool',
            },
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['business', 'status'], name='agents_agen_busines_99de29_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentsetting',
            constraint=models.UniqueConstraint(fields=('agent', 'key'), name='unique_agent_setting_key'),
        ),
        migrations.AddConstraint(
            model_name='agenttool',
            constraint=models.UniqueConstraint(fields=('agent', 'tool_name'), name='unique_agent_tool'),
        ),
    ]
