# Generated by Django 5.2.17 on 2026-09-28 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('max_agents', models.PositiveIntegerField(blank=True, help_text='Null = unlimited.', null=True)),
                ('max_messages_per_month', models.PositiveIntegerField(blank=True, help_text='Null = unlimited.', null=True)),
                ('max_knowledge_documents', models.PositiveIntegerField(blank=True, help_text='Null = unlimited.', null=True)),
                ('max_team_members', models.PositiveIntegerField(blank=True, help_text='Null = unlimited.', null=True)),
                ('trial_days', models.PositiveIntegerField(default=14)),
                ('is_default', models.BooleanField(default=False, help_text="The plan a new business's trial subscription starts on.")),
                ('is_public', models.BooleanField(default=True, help_text='Shown to customers as purchasable.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'billing_plan',
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=16)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('manual', 'Manual'), ('stripe', 'Stripe'), ('razorpay', 'Razorpay')], default='manual', max_length=16)),
                ('external_customer_id', models.CharField(blank=True, max_length=255)),
                ('external_subscription_id', models.CharField(blank=True, max_length=255)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
            options={
                'db_table': 'billing_subscription',
                'indexes': [models.Index(fields=['status'], name='billing_sub_status_948046_idx')],
            },
        ),
    ]
