# Generated by Django 5.2.17 on 2026-10-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_default_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='razorpay_plan_id',
            field=models.CharField(blank=True, help_text='Razorpay Plan id this maps to — set once a real account exists.', max_length=64),
        ),
    ]
