# Generated by Django 5.2.17 on 2026-09-25 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('playground', 'Playground'), ('website', 'Website Widget'), ('api', 'Public API'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('slack', 'Slack')], default='playground', max_length=16)),
                ('external_customer_ref', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('waiting', 'Waiting'), ('resolved', 'Resolved'), ('human_handoff', 'Human Handoff')], default='active', max_length=16)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='agents.agent')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.business')),
                ('started_by', models.ForeignKey(blank=True, help_text='Set for playground conversations — the staff user testing the agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversations_conversation',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('ai', 'AI'), ('agent_user', 'Staff'), ('system', 'System')], max_length=16)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('file', 'File')], default='text', max_length=16)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tool_calls', models.JSONField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.business')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'db_table': 'conversations_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='message_attachments/')),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.business')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='conversations.message')),
            ],
            options={
                'db_table': 'conversations_message_attachment',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['business', 'agent', 'status'], name='conversatio_busines_c45a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_4b968d_idx'),
        ),
    ]
