# Generated by Django 5.2.17 on 2026-09-29 17:23

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_alter_agent_options'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('whatsapp', 'WhatsApp')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('external_account_id', models.CharField(blank=True, help_text='e.g. the WhatsApp phone_number_id.', max_length=255)),
                ('credentials', apps.core.fields.EncryptedTextField(blank=True, default='', help_text='JSON-encoded secret credentials — never returned to the client.')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='agents.agent')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.business')),
            ],
            options={
                'db_table': 'integrations_integration',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature_valid', models.BooleanField(default=False)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.business')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='integrations.integration')),
            ],
            options={
                'db_table': 'integrations_webhook_delivery',
            },
        ),
        migrations.AddConstraint(
            model_name='integration',
            constraint=models.UniqueConstraint(fields=('business', 'provider', 'external_account_id'), name='unique_integration_account'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['integration', 'created_at'], name='integration_integra_f0d01a_idx'),
        ),
    ]
